[package]
name = "extremely_rare_letter_scanner"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "extremely_rare_letter_scanner"
path = "src/main.rs"

[dependencies]
colored = "2.0.4"
